In [ ]:
import warnings

warnings.filterwarnings('ignore')

In [44]:
import numpy as np
import pandas as pd



In [46]:
from sklearn.datasets import load_boston

In [47]:
boston = load_boston()
data = boston["data"]


In [31]:
feature_names = boston["feature_names"]
X = pd.DataFrame(data, columns=feature_names)
X.head()

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD    TAX  \
0  0.00632  18.0   2.31   0.0  0.538  6.575  65.2  4.0900  1.0  296.0   
1  0.02731   0.0   7.07   0.0  0.469  6.421  78.9  4.9671  2.0  242.0   
2  0.02729   0.0   7.07   0.0  0.469  7.185  61.1  4.9671  2.0  242.0   
3  0.03237   0.0   2.18   0.0  0.458  6.998  45.8  6.0622  3.0  222.0   
4  0.06905   0.0   2.18   0.0  0.458  7.147  54.2  6.0622  3.0  222.0   

   PTRATIO       B  LSTAT  
0     15.3  396.90   4.98  
1     17.8  396.90   9.14  
2     17.8  392.83   4.03  
3     18.7  394.63   2.94  
4     18.7  396.90   5.33

In [32]:
target = boston["target"]
Y = pd.DataFrame(target, columns=["price"])
Y.head()

price
0   24.0
1   21.6
2   34.7
3   33.4
4   36.2

In [53]:

from sklearn.model_selection import train_test_split


In [54]:
X_train, X_test,Y_train, Y_test = train_test_split(X, Y, test_size=0.30, random_state=42)

In [55]:
from sklearn.linear_model import LinearRegression

In [56]:
lr = LinearRegression()

In [57]:
lr.fit(X_train, Y_train)

LinearRegression()

In [58]:
y_pred_lr = lr.predict(X_test)
check_test_lr = pd.DataFrame({
    "Y_test": Y_test["price"], 
    "Y_pred_lr": y_pred_lr.flatten()})

check_test_lr.head()

Y_test  Y_pred_lr
173    23.6  28.648960
274    32.4  36.495014
491    13.6  15.411193
72     22.8  25.403213
452    16.1  18.855280

In [59]:
from sklearn.metrics import mean_squared_error

mean_squared_error_lr = mean_squared_error(check_test_lr["Y_pred_lr"], check_test_lr["Y_test"])
print(mean_squared_error_lr)

21.517444231177226


In [ ]:
"задание 2"

In [60]:
from sklearn.ensemble import RandomForestRegressor

In [64]:
clf = RandomForestRegressor(n_estimators=1000, max_depth=12, random_state=42)

In [65]:
clf.fit(X_train, Y_train.values[:, 0])

RandomForestRegressor(max_depth=12, n_estimators=1000, random_state=42)

In [68]:
y_pred_clf = clf.predict(X_test)
check_test_clf = pd.DataFrame({
    "Y_test": Y_test["price"], 
    "Y_pred_clf": y_pred_clf.flatten()})

check_test_clf.head()

Y_test  Y_pred_clf
173    23.6   22.806412
274    32.4   31.131464
491    13.6   16.339125
72     22.8   23.810726
452    16.1   17.139521

In [69]:
mean_squared_error_clf = mean_squared_error(check_test_clf["Y_pred_clf"], check_test_clf["Y_test"])
print(mean_squared_error_clf)

9.334548946165196


In [70]:
print(mean_squared_error_lr, mean_squared_error_clf)

21.517444231177226 9.334548946165196


In [ ]:
"задание 3"

In [71]:
print(clf.feature_importances_)

[0.03167574 0.00154252 0.00713813 0.00123624 0.01426897 0.40268179
 0.01429864 0.06397257 0.00528122 0.01152493 0.01808108 0.01245085
 0.41584732]


In [72]:
feature_importance = pd.DataFrame({'name':X.columns, 
                                   'feature_importance':clf.feature_importances_}, 
                                  columns=['feature_importance', 'name'])
feature_importance

feature_importance     name
0             0.031676     CRIM
1             0.001543       ZN
2             0.007138    INDUS
3             0.001236     CHAS
4             0.014269      NOX
5             0.402682       RM
6             0.014299      AGE
7             0.063973      DIS
8             0.005281      RAD
9             0.011525      TAX
10            0.018081  PTRATIO
11            0.012451        B
12            0.415847    LSTAT

In [73]:
feature_importance.nlargest(2, 'feature_importance')

feature_importance   name
12            0.415847  LSTAT
5             0.402682     RM

In [ ]:
"задание 4"сделать не возможно : не хватает объема диска в ноутбуке!

In [ ]:
**Задание на повторение материала

In [10]:
import numpy as np


In [11]:
a= np.arange(12,24)
a

array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23])

In [14]:
a_1 = a.reshape(2,6)
a_1

array([[12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [15]:
a_2 = a.reshape(3,4)
a_2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [16]:
a_3 = a.reshape(4,3)
a_3

array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

In [24]:
a_4=a.reshape(6,2)
a_4

array([[12, 13],
       [14, 15],
       [16, 17],
       [18, 19],
       [20, 21],
       [22, 23]])

In [19]:
a_5=a.reshape(12,1)
a_5

array([[12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23]])

In [25]:
a_6 = a.reshape(3,-1)
a_6

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [26]:
a_7 = a.reshape(4,-1)
a_7

array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

In [27]:
a_8 = a.reshape(6,-1)
a_8

array([[12, 13],
       [14, 15],
       [16, 17],
       [18, 19],
       [20, 21],
       [22, 23]])

In [28]:
a_9 = a.reshape(-1,4)
a_9

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [29]:
a_10 = a.reshape(-1,3)
a_10

array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

In [31]:
a_11 = np.random.randn(3, 4)
a_11

array([[-1.08237751,  0.85017363,  0.96485691, -0.59011798],
       [ 1.25937054, -0.40404537, -2.06898514,  1.15910094],
       [ 0.8455952 , -0.88796441, -0.43251523, -0.11152918]])

In [32]:
b_11 = a_11.flatten()
b_11

array([-1.08237751,  0.85017363,  0.96485691, -0.59011798,  1.25937054,
       -0.40404537, -2.06898514,  1.15910094,  0.8455952 , -0.88796441,
       -0.43251523, -0.11152918])

In [34]:
a = np.arange(20,0,-2)
a

array([20, 18, 16, 14, 12, 10,  8,  6,  4,  2])

In [35]:
b = np.arange(20, 1, -2)
b

array([20, 18, 16, 14, 12, 10,  8,  6,  4,  2])

In [38]:
a = np.zeros((3, 2))
b = np.ones((2, 2))
print('Массив a ', a, sep='\n')
print('Массив b ', b, sep='\n')

Массив a 
[[0. 0.]
 [0. 0.]
 [0. 0.]]
Массив b 
[[1. 1.]
 [1. 1.]]


In [39]:
v = np.concatenate((a, b), axis = 0)
v

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [1., 1.],
       [1., 1.]])

In [40]:
v.size


10

In [42]:
a=np.arange(0,12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [54]:
A=a.reshape(4,3) 
A

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [55]:
At = A.transpose()
At

array([[ 0,  3,  6,  9],
       [ 1,  4,  7, 10],
       [ 2,  5,  8, 11]])

In [56]:
B = np.dot(A, At)
B

array([[  5,  14,  23,  32],
       [ 14,  50,  86, 122],
       [ 23,  86, 149, 212],
       [ 32, 122, 212, 302]])

In [46]:
B.size

9

In [ ]:
"не получится,определитель матрицы равен нулю"

In [47]:
B = np.dot(A, At)
B
    

array([[ 14,  38,  62],
       [ 38, 126, 214],
       [ 62, 214, 366]])

In [51]:
c = np.arange(0, 16)
c

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [49]:
np.sqrt(c.size)

4.0

In [50]:
C=c.reshape(4,4)
C

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [53]:
B

array([[ 14,  38,  62],
       [ 38, 126, 214],
       [ 62, 214, 366]])

In [57]:
D = 10 * C + B
D

array([[  5,  24,  43,  62],
       [ 54, 100, 146, 192],
       [103, 176, 249, 322],
       [152, 252, 352, 452]])

In [58]:
np.linalg.det(D)

5.18953807259442e-26

In [59]:
D_inv = np.linalg.inv(D)
D_inv

array([[ 4.66062690e+13, -1.49229688e+13, -1.09972869e+14,
         7.82895692e+13],
       [ 1.63480451e+14, -3.81454387e+14,  2.72467419e+14,
        -5.44934838e+13],
       [-4.66779710e+14,  8.07677680e+14, -2.15016230e+14,
        -1.25881740e+14],
       [ 2.56692989e+14, -4.11300324e+14,  5.25216801e+13,
         1.02085655e+14]])

In [60]:
mask_positive = D_inv > 0
mask_negative = D_inv < 0
D_inv[mask_positive] = 1
D_inv[mask_negative] = 0
D_inv

array([[1., 0., 0., 1.],
       [1., 0., 1., 0.],
       [0., 1., 0., 0.],
       [1., 0., 1., 1.]])

In [61]:
E = np.where(D_inv, B, C)
E

array([[  5,   1,   2,  32],
       [ 14,   5,  86,   7],
       [  8,  86,  10,  11],
       [ 32,  13, 212, 302]])